---
title: "Ridge Regression with Custom Function"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Ridge Regression with Custom Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

# Introduction

This vignette demonstrates how to do ridge regression using the `regmodelsuite` package.

```{r setup}
library(regmodelsuite)
```

## Example data

```{r}
set.seed(21)
n <- 100
d <- 10
testlambda <- 0.1

#data X independent and equally distributed on [0,1]
X <- matrix(runif(n * d), n, d)

#real values of beta
beta <- runif(d, min = -1, max = 1) 

#measured y with normally distributed measurement error N(0,0.3^2)
y <- X %*% real_ridge + rnorm(n, mean = 0, sd = 0.3)

#datafram
df <- data.frame(X)
df$y <- y
```

## Basic usage of the ridge function

```{r}
ridge <- regmodel(data=df, model = "ridge", lambda = testlambda)
print(ridge)
```

You can also plot your ridgeobject:

```{r}
plot(ridge)
```
